/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.prefs.Preferences;
import utils.FileHandler;

/**
 *
 * @author felipe-schmidt
 */
public class MarketLabelGenerator extends javax.swing.JFrame {

    /**
     * Creates new form MarketLabelGenerator
     */
    public MarketLabelGenerator() {
        initComponents();
        loadUserPreferences();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonLabelCreation = new javax.swing.ButtonGroup();
        jTabbedPane = new javax.swing.JTabbedPane();
        panelCreateLabels = new javax.swing.JPanel();
        labelInputFile = new javax.swing.JLabel();
        fieldInputFilePath = new javax.swing.JTextField();
        buttonSelectInputFile = new javax.swing.JButton();
        labelOutputFile = new javax.swing.JLabel();
        fieldOutputFilePath = new javax.swing.JTextField();
        buttonSelectOutputFile = new javax.swing.JButton();
        radioEverything = new javax.swing.JRadioButton();
        radioUpdates = new javax.swing.JRadioButton();
        labelGenerate = new javax.swing.JLabel();
        panelLoadModel = new javax.swing.JPanel();
        labelModelFile = new javax.swing.JLabel();
        fieldModelFilePath = new javax.swing.JTextField();
        buttonSelectModelFile = new javax.swing.JButton();
        panelSetup = new javax.swing.JPanel();
        labelIdColumn = new javax.swing.JLabel();
        labelNameColumn = new javax.swing.JLabel();
        labelPriceColumn = new javax.swing.JLabel();
        labelProductRow = new javax.swing.JLabel();
        fieldIdColumn = new javax.swing.JTextField();
        fieldNameColumn = new javax.swing.JTextField();
        fieldPriceColumn = new javax.swing.JTextField();
        fieldProductRow = new javax.swing.JTextField();
        labelMarketLabelGenerator = new javax.swing.JLabel();
        comboBoxLanguageSelector = new javax.swing.JComboBox<>();
        labelLanguage = new javax.swing.JLabel();

        buttonLabelCreation.add(radioEverything);
        buttonLabelCreation.add(radioUpdates);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelInputFile.setText("Input File");

        fieldInputFilePath.setEnabled(false);
        fieldInputFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldInputFilePathActionPerformed(evt);
            }
        });

        buttonSelectInputFile.setText("Select File");
        buttonSelectInputFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectInputFileActionPerformed(evt);
            }
        });

        labelOutputFile.setText("Output File");

        fieldOutputFilePath.setEnabled(false);
        fieldOutputFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldOutputFilePathActionPerformed(evt);
            }
        });

        buttonSelectOutputFile.setText("Select File");
        buttonSelectOutputFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectOutputFileActionPerformed(evt);
            }
        });

        radioEverything.setText("Everything");

        radioUpdates.setSelected(true);
        radioUpdates.setText("Updates");
        radioUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioUpdatesActionPerformed(evt);
            }
        });

        labelGenerate.setText("Generate");

        javax.swing.GroupLayout panelCreateLabelsLayout = new javax.swing.GroupLayout(panelCreateLabels);
        panelCreateLabels.setLayout(panelCreateLabelsLayout);
        panelCreateLabelsLayout.setHorizontalGroup(
            panelCreateLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateLabelsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCreateLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCreateLabelsLayout.createSequentialGroup()
                        .addComponent(labelInputFile)
                        .addGap(18, 18, 18)
                        .addComponent(fieldInputFilePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonSelectInputFile))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCreateLabelsLayout.createSequentialGroup()
                        .addGroup(panelCreateLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelOutputFile)
                            .addComponent(labelGenerate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelCreateLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCreateLabelsLayout.createSequentialGroup()
                                .addComponent(radioUpdates)
                                .addGap(18, 18, 18)
                                .addComponent(radioEverything))
                            .addComponent(fieldOutputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSelectOutputFile)))
                .addContainerGap())
        );
        panelCreateLabelsLayout.setVerticalGroup(
            panelCreateLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCreateLabelsLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(panelCreateLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInputFile)
                    .addComponent(fieldInputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSelectInputFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOutputFile)
                    .addComponent(fieldOutputFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSelectOutputFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCreateLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioEverything)
                    .addComponent(radioUpdates)
                    .addComponent(labelGenerate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Create Labels", panelCreateLabels);

        labelModelFile.setText("Model File");

        fieldModelFilePath.setEnabled(false);
        fieldModelFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldModelFilePathActionPerformed(evt);
            }
        });

        buttonSelectModelFile.setText("Select File");
        buttonSelectModelFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSelectModelFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoadModelLayout = new javax.swing.GroupLayout(panelLoadModel);
        panelLoadModel.setLayout(panelLoadModelLayout);
        panelLoadModelLayout.setHorizontalGroup(
            panelLoadModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoadModelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelModelFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fieldModelFilePath, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSelectModelFile)
                .addContainerGap())
        );
        panelLoadModelLayout.setVerticalGroup(
            panelLoadModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoadModelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelLoadModelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModelFile)
                    .addComponent(fieldModelFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSelectModelFile))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Load Model", panelLoadModel);

        labelIdColumn.setText("ID Column");

        labelNameColumn.setText("Name Column");

        labelPriceColumn.setText("Price Column");

        labelProductRow.setText("Product Row");

        fieldPriceColumn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPriceColumnActionPerformed(evt);
            }
        });

        fieldProductRow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldProductRowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSetupLayout = new javax.swing.GroupLayout(panelSetup);
        panelSetup.setLayout(panelSetupLayout);
        panelSetupLayout.setHorizontalGroup(
            panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNameColumn)
                    .addComponent(labelPriceColumn)
                    .addComponent(labelProductRow)
                    .addComponent(labelIdColumn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fieldIdColumn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addGroup(panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fieldProductRow, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(fieldPriceColumn)
                        .addComponent(fieldNameColumn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSetupLayout.setVerticalGroup(
            panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSetupLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdColumn)
                    .addComponent(fieldIdColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNameColumn)
                    .addComponent(fieldNameColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPriceColumn)
                    .addComponent(fieldPriceColumn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSetupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProductRow)
                    .addComponent(fieldProductRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Setup", panelSetup);

        labelMarketLabelGenerator.setText("Market Label Generator");

        comboBoxLanguageSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EN", "DE", "PT" }));
        comboBoxLanguageSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLanguageSelectorActionPerformed(evt);
            }
        });

        labelLanguage.setText("Language");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelMarketLabelGenerator)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLanguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxLanguageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMarketLabelGenerator)
                    .addComponent(comboBoxLanguageSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLanguage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldInputFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldInputFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldInputFilePathActionPerformed

    private void fieldOutputFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldOutputFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldOutputFilePathActionPerformed

    private void fieldModelFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldModelFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldModelFilePathActionPerformed

    private void fieldPriceColumnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPriceColumnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPriceColumnActionPerformed

    private void fieldProductRowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldProductRowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldProductRowActionPerformed

    private void buttonSelectInputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectInputFileActionPerformed
        fieldInputFilePath.setText(FileHandler.displayFileSelector());
    }//GEN-LAST:event_buttonSelectInputFileActionPerformed

    private void buttonSelectOutputFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectOutputFileActionPerformed
        fieldOutputFilePath.setText(FileHandler.displayFileSelector());
    }//GEN-LAST:event_buttonSelectOutputFileActionPerformed

    private void buttonSelectModelFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSelectModelFileActionPerformed
        fieldModelFilePath.setText(FileHandler.displayFileSelector());
    }//GEN-LAST:event_buttonSelectModelFileActionPerformed

    private void radioUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioUpdatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioUpdatesActionPerformed

    private void comboBoxLanguageSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLanguageSelectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxLanguageSelectorActionPerformed

    private void loadUserPreferences() {
        //Preferences prefs = Preferences.userNodeForPackage(this);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MarketLabelGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MarketLabelGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MarketLabelGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MarketLabelGenerator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MarketLabelGenerator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonLabelCreation;
    private javax.swing.JButton buttonSelectInputFile;
    private javax.swing.JButton buttonSelectModelFile;
    private javax.swing.JButton buttonSelectOutputFile;
    private javax.swing.JComboBox<String> comboBoxLanguageSelector;
    private javax.swing.JTextField fieldIdColumn;
    private javax.swing.JTextField fieldInputFilePath;
    private javax.swing.JTextField fieldModelFilePath;
    private javax.swing.JTextField fieldNameColumn;
    private javax.swing.JTextField fieldOutputFilePath;
    private javax.swing.JTextField fieldPriceColumn;
    private javax.swing.JTextField fieldProductRow;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel labelGenerate;
    private javax.swing.JLabel labelIdColumn;
    private javax.swing.JLabel labelInputFile;
    private javax.swing.JLabel labelLanguage;
    private javax.swing.JLabel labelMarketLabelGenerator;
    private javax.swing.JLabel labelModelFile;
    private javax.swing.JLabel labelNameColumn;
    private javax.swing.JLabel labelOutputFile;
    private javax.swing.JLabel labelPriceColumn;
    private javax.swing.JLabel labelProductRow;
    private javax.swing.JPanel panelCreateLabels;
    private javax.swing.JPanel panelLoadModel;
    private javax.swing.JPanel panelSetup;
    private javax.swing.JRadioButton radioEverything;
    private javax.swing.JRadioButton radioUpdates;
    // End of variables declaration//GEN-END:variables
}
